"""Per-stage state schemas for the multi-subgraph trading pipeline.

Each stage subgraph declares only the channels it actually reads or writes.
The parent graph (AgentState) hands its full state to every subgraph node;
LangGraph filters it down to the subgraph's declared channels, runs the
stage, then merges the written channels back into the parent state.

Keeping every schema a strict subset of AgentState means:

- each stage is independently testable with a tiny fake state,
- no stage can accidentally reach into another stage's private data,
- the parent graph stays a thin sequential orchestrator, and
- checkpoints taken inside any subgraph remain resumable from the parent.
"""

from __future__ import annotations

from typing import Annotated

from typing_extensions import TypedDict

from langgraph.graph import MessagesState
from langgraph.graph.message import add_messages

from tradingagents.agents.utils.agent_states import (
    InvestDebateState,
    RiskDebateState,
    merge_verification_state,
)

# ---------------------------------------------------------------------------
# Stage 1: Analyst Team
# ---------------------------------------------------------------------------


class AnalystTeamSubgraphState(MessagesState):
    """Selected analysts run in sequence; each loops with its tool node.

    Channels written: the four analyst reports (flow back to the parent so
    the Research Debate and Risk Debate stages can read them).
    """

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst (基本面)"]
    technical_report: Annotated[str, "Report from the Technical Analyst (技术面)"]
    game_theory_report: Annotated[str, "Report from the Game Theory Analyst (博弈面)"]
    news_sentiment_report: Annotated[str, "Report from the News & Sentiment Analyst (新闻舆情)"]
    fundamentals_claims: Annotated[list, "Structured claims with sources from the Fundamentals Analyst"]
    technical_claims: Annotated[list, "Structured claims with sources from the Technical Analyst"]
    game_theory_claims: Annotated[list, "Structured claims with sources from the Game Theory Analyst"]
    verification_state: Annotated[dict, merge_verification_state]
    # Per-analyst parallel message channels (analyst <-> tools loops)
    messages_fundamentals: Annotated[list, add_messages]
    messages_technical: Annotated[list, add_messages]
    messages_game_theory: Annotated[list, add_messages]
    messages_news_sentiment: Annotated[list, add_messages]


# ---------------------------------------------------------------------------
# Stage 2: Research Debate (bull vs bear + Research Manager)
# ---------------------------------------------------------------------------


class ResearchDebateSubgraphState(MessagesState):
    """Bull/bear researchers trade arguments; Research Manager synthesises
    the debate into an investment_plan."""

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst (基本面)"]
    technical_report: Annotated[str, "Report from the Technical Analyst (技术面)"]
    game_theory_report: Annotated[str, "Report from the Game Theory Analyst (博弈面)"]
    news_sentiment_report: Annotated[str, "Report from the News & Sentiment Analyst (新闻舆情)"]
    investment_debate_state: Annotated[InvestDebateState, "Bull/bear debate progress"]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]


# ---------------------------------------------------------------------------
# Stage 3: Trader
# ---------------------------------------------------------------------------


class TraderSubgraphState(MessagesState):
    """Turns the Research Manager's investment plan into a concrete
    transaction proposal (trader_investment_plan)."""

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    game_theory_report: Annotated[str, "Report from the Game Theory Analyst (博弈面)"]
    news_sentiment_report: Annotated[str, "Report from the News & Sentiment Analyst (新闻舆情)"]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    sender: Annotated[str, "Agent that sent this message"]


# ---------------------------------------------------------------------------
# Stage 4: Risk Debate (aggressive / conservative / neutral)
# ---------------------------------------------------------------------------


class RiskDebateSubgraphState(MessagesState):
    """The three risk analysts debate the Trader's proposal until the debate
    budget is exhausted; the subgraph then hands control back to the parent."""

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst (基本面)"]
    technical_report: Annotated[str, "Report from the Technical Analyst (技术面)"]
    game_theory_report: Annotated[str, "Report from the Game Theory Analyst (博弈面)"]
    news_sentiment_report: Annotated[str, "Report from the News & Sentiment Analyst (新闻舆情)"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    risk_debate_state: Annotated[RiskDebateState, "Risk debate progress"]


# ---------------------------------------------------------------------------
# Stage 5: Portfolio Manager
# ---------------------------------------------------------------------------


class PortfolioManagerSubgraphState(MessagesState):
    """Portfolio Manager renders the final, non-delegable decision
    (final_trade_decision) from the risk debate + both plans."""

    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    investment_plan: Annotated[str, "Plan generated by the Research Manager"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]
    risk_debate_state: Annotated[RiskDebateState, "Risk debate progress"]
    past_context: Annotated[str, "Memory log context injected at run start"]
    final_trade_decision: Annotated[str, "Final decision made by the Portfolio Manager"]
