from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState
from langgraph.graph.message import add_messages


def merge_verification_state(left: dict, right: dict) -> dict:
    """Reducer for the verification_state channel.

    The fact-checkers of the parallel analysts update this channel
    concurrently; each writes only its own analyst key, so merging by key
    is safe and last-write-wins per analyst.
    """
    if not left:
        return right
    if not right:
        return left
    merged = dict(left)
    merged.update(right)
    return merged


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    # Anchor ticker captured at run start; immutable across the pipeline.
    # TickerGuard nodes verify company_of_interest never diverges from it.
    input_ticker: Annotated[str, "Anchor ticker this run was started with"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # 4 analyst reports
    fundamentals_report: Annotated[str, "Report from the Fundamentals Analyst (基本面)"]
    technical_report: Annotated[str, "Report from the Technical Analyst (技术面)"]
    game_theory_report: Annotated[str, "Report from the Game Theory Analyst (博弈面)"]
    news_sentiment_report: Annotated[str, "Report from the News & Sentiment Analyst (新闻舆情)"]

    # Structured claims (AnalystClaim dicts) backing each verified report.
    # Populated by the analyst finalizers; consumed by the fact-checker nodes.
    fundamentals_claims: Annotated[list, "Structured claims with sources from the Fundamentals Analyst"]
    technical_claims: Annotated[list, "Structured claims with sources from the Technical Analyst"]
    game_theory_claims: Annotated[list, "Structured claims with sources from the Game Theory Analyst"]

    # Per-analyst message channels: the four analysts run in PARALLEL inside
    # the Analyst Team stage, so each keeps its own tool-loop conversation
    # (analyst <-> tools) without cross-contamination. The shared 'messages'
    # channel remains for the downstream stages.
    messages_fundamentals: Annotated[list, add_messages]
    messages_technical: Annotated[list, add_messages]
    messages_game_theory: Annotated[list, add_messages]
    messages_news_sentiment: Annotated[list, add_messages]

    # Fact-checker bookkeeping per analyst: attempts / passed / feedback / items.
    # Merged by analyst key because the parallel fact-checkers write concurrently.
    verification_state: Annotated[dict, merge_verification_state]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
